name = "distillpub"
license = "MIT"
licenselink = "https://github.com/grungy/distillpub-template/blob/master/LICENSE"
description = "Hugo theme for Distill articles"
homepage = "https://github.com/grungy/distillpub-template"
tags = []
features = []
min_version = "0.55"
